GET https://localhost:5001/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjcyNTI1ZjA0NWI4ZGY3MmZlZjM4YiIsIm5iZiI6MTc0MDA1NzY1MSwiZXhwIjoxNzQwNjYyNDUxLCJpYXQiOjE3NDAwNTc2NTF9.J3mvL3me_oiWWbqRhCYD3gS7Lc0REnEPfYks1AYHIMM


###
###
GET https://localhost:5001/api/books

###
GET https://localhost:5001/api/books/7

###

###
POST https://localhost:5001/api/signup
Content-Type: application/json

{
  "username": "test12",
  "email":"test12@test.com",
  "password": "test12"
}

###
POST https://localhost:5001/api/login
Content-Type: application/json

{
  "email":"test12@test.com",
  "password": "test12"
}
###
POST https://localhost:5001/api/books
Content-Type: application/json

{
  "Title": "How Children Succeed: Grit, Curiosity, and the Hidden Power of Character (Hardcover)",
  "Price": 100,
  "Author": "Paul Tough",
  "User_Id": 1 
}

###
POST https://localhost:5001/api/books
Content-Type: application/json

{
  "Title": "The Let Them Theory: A Life-Changing Tool That Millions of People Can't Stop Talking About",
  "Price": 82,
  "Author": "Mel Robbins",
  "User_Id": 1 
}